apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: 2048-game
          image: 2048-game:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  type: NodePort
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30013
